# Generated by Django 4.2.30 on 2026-04-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('athleteid', models.AutoField(db_column='athleteid', primary_key=True, serialize=False)),
                ('athlete_name', models.CharField(db_column='athletename', max_length=30)),
                ('phone', models.CharField(db_column='phone', max_length=10)),
                ('birth_date', models.DateField(db_column='birthdate')),
                ('grad_year', models.CharField(db_column='gradyear', max_length=4)),
            ],
            options={
                'db_table': 'athletes',
                'ordering': ['athlete_name'],
            },
        ),
    ]
