# Generated by Django 4.2.30 on 2026-04-24 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('workoutid', models.AutoField(db_column='workoutid', primary_key=True, serialize=False)),
                ('workout_name', models.CharField(db_column='workoutname', max_length=20)),
                ('workout_type', models.CharField(db_column='workouttype', max_length=20)),
            ],
            options={
                'db_table': 'workouts',
                'ordering': ['workout_type', 'workout_name'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutRecord',
            fields=[
                ('athlete', models.ForeignKey(db_column='athleteid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.athlete')),
                ('duration', models.CharField(blank=True, db_column='duration', max_length=20, null=True)),
                ('pace', models.CharField(blank=True, db_column='pace', max_length=20, null=True)),
                ('average_hr', models.IntegerField(blank=True, db_column='averagehr', null=True)),
                ('workout', models.ForeignKey(db_column='workoutid', on_delete=django.db.models.deletion.CASCADE, to='core.workout')),
            ],
            options={
                'db_table': 'workoutrecords',
                'unique_together': {('athlete', 'workout')},
            },
        ),
    ]
